// Microplastics Knowledge Graph (v2) - Neo4j load script
// Generated from mpkg_output_v2.json by mpkg_to_cypher.py

// Clean slate (comment out to append instead):
MATCH (n:MPKG) DETACH DELETE n;

// Uniqueness constraint on node id:
CREATE CONSTRAINT mpkg_id IF NOT EXISTS FOR (n:MPKG) REQUIRE n.id IS UNIQUE;

// --- Nodes ---
CREATE (:MPKG:Study {id: 'study_neurotoxicity_following_exposure_review', title: 'Neurotoxicity Following Exposure to Micro and Nanoplastics', design: 'review', exposure_context: 'neurotoxic implications of nanoplastics across various species and in vitro settings', notes: 'The review includes studies published between 2015 and 2024.'});
CREATE (:MPKG:Polymer {id: 'polymer_polystyrene', name: 'polystyrene', synonyms: '["PS"]'});
CREATE (:MPKG:Polymer {id: 'polymer_amino_modified_polystyrene', name: 'amino-modified polystyrene', synonyms: '["PS-NH2"]'});
CREATE (:MPKG:Polymer {id: 'polymer_polyethylene', name: 'polyethylene'});
CREATE (:MPKG:Polymer {id: 'polymer_low_density_polyethylene', name: 'low-density polyethylene', synonyms: '["LDPE"]'});
CREATE (:MPKG:Shape {id: 'shape_bead', label: 'bead', synonyms: '["microbead"]'});
CREATE (:MPKG:ParticleSizeClass {id: 'size_100_to_200_um', label: '100-200 μm', min_micrometer: 100, max_micrometer: 200, bin_type: 'micro'});
CREATE (:MPKG:ParticleSizeClass {id: 'size_1_um', label: '1 μm', min_micrometer: 1, max_micrometer: 1, bin_type: 'micro'});
CREATE (:MPKG:ParticleSizeClass {id: 'size_10_um', label: '10 μm', min_micrometer: 10, max_micrometer: 10, bin_type: 'micro'});
CREATE (:MPKG:ParticleSizeClass {id: 'size_20_um', label: '20 μm', min_micrometer: 20, max_micrometer: 20, bin_type: 'micro'});
CREATE (:MPKG:ParticleSizeClass {id: 'size_100_um', label: '100 μm', min_micrometer: 100, max_micrometer: 100, bin_type: 'micro'});
CREATE (:MPKG:ParticleSizeClass {id: 'size_1_to_5_um', label: '1-5 μm', min_micrometer: 1, max_micrometer: 5, bin_type: 'micro'});
CREATE (:MPKG:ParticleSizeClass {id: 'size_0_1_um', label: '0.1 μm', min_micrometer: 0.1, max_micrometer: 0.1, bin_type: 'micro'});
CREATE (:MPKG:ParticleSizeClass {id: 'size_5_um', label: '5 μm', min_micrometer: 5, max_micrometer: 5, bin_type: 'micro'});
CREATE (:MPKG:Method {id: 'method_fluorescence_spectrometer', method_class: 'fluorescence spectrometer analysis', identification_capability: 'confirmed absorption and presence of particles in freeze-dried tissues'});
CREATE (:MPKG:Method {id: 'method_confocal_microscopy', method_class: 'confocal microscopy', identification_capability: 'observed accumulation of particles'});
CREATE (:MPKG:Method {id: 'method_light_microscopy', method_class: 'light microscopy', identification_capability: 'detected microplastic particles'});
CREATE (:MPKG:Method {id: 'method_infrared_spectroscopy', method_class: 'infrared spectroscopy', identification_capability: 'detected microplastic particles'});
CREATE (:MPKG:Method {id: 'method_polarized_light_microscopy', method_class: 'polarized light microscopy', identification_capability: 'identified plastic particles'});
CREATE (:MPKG:Method {id: 'method_fluorescence_microscopy', method_class: 'fluorescence microscopy', identification_capability: 'detected fluorescent microparticles'});
CREATE (:MPKG:Biomarker {id: 'biomarker_acetylcholinesterase_activity', name: 'acetylcholinesterase activity', direction_of_change: 'variable', citations_ref: '["[42]", "[85]", "[87]", "[89]", "[90]", "[91]"]'});
CREATE (:MPKG:Biomarker {id: 'biomarker_caspase_3', name: 'caspase-3 signals', tissue_matrix: 'mouse brain tissue', direction_of_change: 'increase', citations_ref: '["[41]"]'});
CREATE (:MPKG:Biomarker {id: 'biomarker_tnf_alpha', name: 'TNF-α', tissue_matrix: 'mouse brain tissue', direction_of_change: 'increase', citations_ref: '["[41]"]'});
CREATE (:MPKG:Biomarker {id: 'biomarker_il_6', name: 'IL-6', tissue_matrix: 'mouse brain tissue', direction_of_change: 'increase', citations_ref: '["[41]"]'});
CREATE (:MPKG:Biomarker {id: 'biomarker_catalase_activity', name: 'catalase activity', direction_of_change: 'variable', citations_ref: '["[85]", "[86]", "[87]", "[93]"]'});
CREATE (:MPKG:Biomarker {id: 'biomarker_malondialdehyde_levels', name: 'malondialdehyde levels', direction_of_change: 'increase', citations_ref: '["[85]"]'});
CREATE (:MPKG:Biomarker {id: 'biomarker_dopamine_levels', name: 'dopamine levels', direction_of_change: 'increase', citations_ref: '["[86]"]'});
CREATE (:MPKG:Biomarker {id: 'biomarker_superoxide_dismutase_activity', name: 'superoxide dismutase activity', direction_of_change: 'increase', citations_ref: '["[87]"]'});
CREATE (:MPKG:Biomarker {id: 'biomarker_glutathione_s_transferase_activity', name: 'Glutathione-S-transferase activity', direction_of_change: 'variable', citations_ref: '["[87]", "[93]"]'});
CREATE (:MPKG:Biomarker {id: 'biomarker_lipid_peroxidation', name: 'lipid peroxidation', direction_of_change: 'variable', citations_ref: '["[42]", "[87]", "[91]"]'});
CREATE (:MPKG:Biomarker {id: 'biomarker_atp_levels', name: 'ATP levels', tissue_matrix: 'mouse liver', direction_of_change: 'decrease', citations_ref: '["[42]"]'});
CREATE (:MPKG:Biomarker {id: 'biomarker_ldh_activity', name: 'LDH activity', tissue_matrix: 'mouse liver', direction_of_change: 'increase', citations_ref: '["[42]"]'});
CREATE (:MPKG:Mechanism {id: 'mechanism_oxidative_stress', label: 'oxidative_stress', evidence_type: 'review', key_biomarkers: '["catalase activity", "malondialdehyde levels", "superoxide dismutase activity", "lipid peroxidation"]', notes: 'The paper explicitly reports oxidative stress or oxidative damage in multiple summarized studies.'});
CREATE (:MPKG:Mechanism {id: 'mechanism_inflammation', label: 'inflammation', evidence_type: 'review', key_biomarkers: '["TNF-α", "IL-6"]', notes: 'The paper reports upregulated TNF-α and IL-6 in mouse brain tissues exposed to PS-NH2.'});
CREATE (:MPKG:Mechanism {id: 'mechanism_metabolic_disturbance', label: 'metabolic_disturbance', evidence_type: 'review', key_biomarkers: '["ATP levels", "LDH activity"]', notes: 'The paper reports dose-dependent alterations in energy metabolism in mouse liver.'});
CREATE (:MPKG:Mechanism {id: 'mechanism_genotoxicity', label: 'genotoxicity', evidence_type: 'review', notes: 'The paper explicitly states that polystyrene microbeads did not cause genotoxic effects in Dreissena polymorpha.'});
CREATE (:MPKG:Mechanism {id: 'mechanism_apoptosis', label: 'other', evidence_type: 'review', key_biomarkers: '["caspase-3 signals"]', notes: 'Apoptosis (neuron cell death): caspase-3, a marker for neuron cell apoptosis, showed increased signals in mouse brain tissues exposed to PS-NH2.', citations_ref: '["[41]"]'});
CREATE (:MPKG:ClinicalOutcome {id: 'outcome_behavioral_changes', label: 'behavioral changes', outcome_type: 'other', strength_of_evidence: 'limited', causal_confidence: 'low', notes: 'The abstract states that exposure could inhibit acetylcholinesterase activity and alter neurotransmitter levels, potentially contributing to observed behavioral changes.'});
CREATE (:MPKG:ClinicalOutcome {id: 'outcome_neurological_disorders', label: 'neurological disorders', outcome_type: 'diagnosis', strength_of_evidence: 'limited', causal_confidence: 'low', notes: 'The abstract states that exposure to nanoplastics may lead to oxidative stress, potentially causing cell damage and raising the risk of developing neurological disorders.'});
CREATE (:MPKG:ClinicalOutcome {id: 'outcome_lower_survival_lifespan', label: 'lowered survival rates and decreased average lifespan', outcome_type: 'other', strength_of_evidence: 'limited', causal_confidence: 'low', notes: 'Caenorhabditis elegans exposed to spherical polystyrene microplastics showed lowered survival rates and decreased average lifespan.'});
CREATE (:MPKG:TissueOrgan {id: 'tissue_brain', label: 'brain', species: 'mouse', vulnerability_notes: 'Mouse brain tissues exposed to PS-NH2 showed increased caspase-3 signals and upregulated TNF-α and IL-6.', citations_ref: '["[41]"]'});
CREATE (:MPKG:TissueOrgan {id: 'tissue_liver', label: 'liver', species: 'mouse', vulnerability_notes: 'Mouse liver showed dose-dependent alterations in energy metabolism, including reduced ATP levels and elevated LDH activity.', citations_ref: '["[42]"]'});
CREATE (:MPKG:ExposurePathway {id: 'exposure_oral', pathway_label: 'ingestion', route: 'oral', population_context: 'humans, fish, and mammals', assumptions_notes: 'The conclusions list ingestion among exposure routes; particles can be taken in by aquatic beings and mammals.'});
CREATE (:MPKG:ExposurePathway {id: 'exposure_inhalation', pathway_label: 'inhalation', route: 'inhalation', population_context: 'humans', assumptions_notes: 'The conclusions list inhalation among exposure routes that need better assessment.'});
CREATE (:MPKG:ExposurePathway {id: 'exposure_nasal_retrograde', pathway_label: 'retrograde transport after nasal exposure', population_context: 'humans', assumptions_notes: 'The conclusions explicitly mention retrograde transport after nasal exposure as an exposure route to assess.'});
CREATE (:MPKG:Observation {id: 'obs_mouse_liver_5um_ps_concentration', metric_type: 'concentration', value: 'approximately 0.2', unit: 'mg/g', notes: 'During the initial week of exposure, 5 μm polystyrene particle concentrations stabilized at approximately 0.2 mg/g in liver.'});
CREATE (:MPKG:Observation {id: 'obs_mouse_kidney_5um_ps_concentration', metric_type: 'concentration', value: 'approximately 1.0', unit: 'mg/g', notes: 'During the initial week of exposure, 5 μm polystyrene particle concentrations stabilized at approximately 1.0 mg/g in kidney.'});
CREATE (:MPKG:Observation {id: 'obs_mouse_gut_5um_ps_concentration', metric_type: 'concentration', value: 'approximately 1.4', unit: 'mg/g', notes: 'During the initial week of exposure, 5 μm polystyrene particle concentrations stabilized at approximately 1.4 mg/g in gut.'});
CREATE (:MPKG:Observation {id: 'obs_mouse_20um_ps_concentration_plateau', metric_type: 'concentration', value: 'about 0.8', unit: 'mg/g', notes: 'For 20 μm particles, the concentration was more consistent across the organs, reaching a plateau at about 0.8 (mg/g; unit inferred from the 5 μm reporting basis in the same study).'});
CREATE (:MPKG:Observation {id: 'obs_earthworm_polyethylene_uptake', metric_type: 'presence_absence', value: 'detected', unit: 'categorical', notes: 'Polyethylene particle uptake was confirmed after 14-28 days at 1.5 g/kg soil.'});
CREATE (:MPKG:Observation {id: 'obs_zebra_mussel_polystyrene_microbeads_accumulation', metric_type: 'presence_absence', value: 'detected', unit: 'categorical', notes: 'Dreissena polymorpha exposed to pristine polystyrene microbeads of 1 μm and 10 μm at concentrations of 1 and 4 × 10^6 MPs/L for six days showed accumulation of particles within the gut lumen and further movement to tissues and hemolymph.'});
CREATE (:MPKG:Observation {id: 'obs_scrobicularia_polystyrene_particles_detected', metric_type: 'presence_absence', value: 'detected', unit: 'categorical', notes: 'Scrobicularia plana exposed to 20 μm polystyrene microplastics at a concentration of 1 mg/L; particles detected in the hemolymph, digestive gland, and gills.'});
CREATE (:MPKG:Observation {id: 'obs_mediterranean_mussel_particles_detected', metric_type: 'presence_absence', value: 'detected', unit: 'categorical', notes: 'Mytilus galloprovincialis exposed to unpolluted and pyrene-contaminated polyethylene and polystyrene microplastics (100 μm, 1.5 g/L) over seven days; plastic particles within the hemolymph, gills, and intestines.'});
CREATE (:MPKG:Observation {id: 'obs_corbicula_polymeric_microspheres_detected', metric_type: 'presence_absence', value: 'detected', unit: 'categorical', notes: 'Corbicula flumina exposed to red fluorescent polymeric microspheres (composition unspecified; 1-5 μm, 0.2 or 0.7 mg/L) for 96 hours; plastic particles inside the digestive tract, gland\'s lumen, connective tissue, hemolymphatic sinuses, and the surface of the gills.'});
CREATE (:MPKG:Observation {id: 'obs_shrimp_polystyrene_particles_detected', metric_type: 'presence_absence', value: 'detected', unit: 'categorical', notes: 'Amphibalanus amphitrite and Artemia franciscana larvae exposed to 0.1 μm fluorescent polystyrene microparticles at 0.001 to 10 mg/L over 24 to 48 hours; plastic particles detectable within larvae.'});
CREATE (:MPKG:Observation {id: 'obs_mouse_brain_caspase3_increased', metric_type: 'presence_absence', value: 'increased', unit: 'categorical', notes: 'Mouse brain tissues exposed to PS-NH2 showed increased caspase-3 signals.'});
CREATE (:MPKG:Observation {id: 'obs_mouse_brain_tnf_il6_upregulated', metric_type: 'presence_absence', value: 'increased', unit: 'categorical', notes: 'Mouse brain tissues exposed to PS-NH2 showed TNF-α and IL-6 upregulation.'});
CREATE (:MPKG:Observation {id: 'obs_zebra_mussel_no_genotoxic_effects', metric_type: 'presence_absence', value: 'absent', unit: 'categorical', notes: 'Polystyrene microbeads did not cause genotoxic effects in Dreissena polymorpha.'});
CREATE (:MPKG:Association {id: 'assoc_nanoplastics_oxidative_stress', relationship: 'suggests', direction: 'increase', evidence_strength: 'limited', consistency_across_studies: 'unknown', study_scope: 'nanoplastics across various species and in vitro settings', causal_confidence: 'low', notes: 'The abstract states: current evidence, although incomplete, suggests that exposure to nanoplastics may lead to oxidative stress.'});
CREATE (:MPKG:Association {id: 'assoc_ache_neurotransmitter_behavioral_changes', relationship: 'suggests', direction: 'variable', evidence_strength: 'limited', consistency_across_studies: 'unknown', causal_confidence: 'low', notes: 'The abstract states that exposure could inhibit acetylcholinesterase activity and alter neurotransmitter levels, potentially contributing to observed behavioral changes.'});
CREATE (:MPKG:Association {id: 'assoc_celegans_polystyrene_exposure_effects', relationship: 'associated_with', direction: 'decrease', evidence_strength: 'limited', consistency_across_studies: 'unknown', causal_confidence: 'low', notes: 'Caenorhabditis elegans exposed to five different spherical polystyrene microplastic sizes (0.1-5 μm) at 1 mg/L showed movement effects, lowered survival rates, and decreased average lifespan; the paper notes no direct proof of ingestion.'});
CREATE (:MPKG:Association {id: 'assoc_neuronal_gene_decline_disruptions_oxidative_stress', relationship: 'associated_with', direction: 'decrease', evidence_strength: 'limited', consistency_across_studies: 'unknown', causal_confidence: 'low', notes: 'The paper states that expression of several neuronal genes declined, which was linked to disruptions in cholinergic and GABA neurons and increased oxidative stress.'});
CREATE (:MPKG:Association {id: 'assoc_rat_40nm_ps_null_behavior_weight', relationship: 'null', direction: 'none', evidence_strength: 'limited', consistency_across_studies: 'unknown', causal_confidence: 'low', notes: 'Male rats chronically exposed over five weeks to 40 nm polystyrene nanoplastics at 1 to 10 mg/kg body weight per day showed no impact on behavior or weight gain, and no evidence was provided of actual uptake.'});
CREATE (:MPKG:Association {id: 'assoc_zebra_mussel_genotoxicity_null', relationship: 'null', direction: 'none', evidence_strength: 'limited', consistency_across_studies: 'unknown', causal_confidence: 'low', notes: 'The paper states that polystyrene microbeads did not cause genotoxic effects in Dreissena polymorpha.'});
CREATE (:MPKG:Study {id: 'study_ref_41', title: 'Primary study [41]: PS-NH2 neurotoxicity in mouse brain', design: 'in_vivo', species: 'mouse', evidence_strength: 'limited', notes: 'Primary study cited by the review. Mouse brain tissues exposed to PS-NH2 showed increased caspase-3 signals and upregulated TNF-alpha and IL-6.', citations_ref: '["[41]"]'});
CREATE (:MPKG:Study {id: 'study_ref_42', title: 'Primary study [42]: polystyrene microplastics in mice (oral gavage)', design: 'in_vivo', species: 'mouse', exposure_context: 'chronic 30-day oral gavage, 5 and 20 um polystyrene microplastics', evidence_strength: 'limited', notes: 'The solely published mice in vivo study cited by the review; particles accumulated in gut, liver, and kidneys.', citations_ref: '["[42]"]'});
CREATE (:MPKG:Study {id: 'study_ref_85', title: 'Primary study [85]: LDPE neurotoxicity in earthworms (Eisenia fetida)', design: 'in_vivo', species: 'Eisenia fetida', exposure_context: 'low-density polyethylene 100-200 um, 0.1-1.5 g/kg soil, up to 28 days', evidence_strength: 'limited', notes: 'Primary study cited by the review; confirmed polyethylene uptake and oxidative stress markers.', citations_ref: '["[85]"]'});
CREATE (:MPKG:Study {id: 'study_ref_86', title: 'Primary study [86]: polystyrene microbeads in zebra mussels (Dreissena polymorpha)', design: 'in_vivo', species: 'Dreissena polymorpha', exposure_context: 'pristine polystyrene microbeads 1 and 10 um, 1 and 4 x 10^6 MPs/L, six days', evidence_strength: 'limited', notes: 'Primary study cited by the review; particles accumulated but caused no genotoxic effects.', citations_ref: '["[86]"]'});
CREATE (:MPKG:HostPopulation {id: 'host_human', label: 'Human', organism_class: 'human', scientific_name: 'Homo sapiens', model_type: 'observational', translational_relevance: 'high', notes: 'Humans are chronically exposed at lower levels; direct human neurotoxicity evidence is lacking.', citations_ref: '["[37]", "[38]", "[39]"]'});
CREATE (:MPKG:HostPopulation {id: 'host_mouse', label: 'Mouse', organism_class: 'mammal', scientific_name: 'Mus musculus', model_type: 'in_vivo', translational_relevance: 'medium', notes: 'Adult mice exposed to polystyrene microplastics (5 and 20 um) and PS-NH2.', citations_ref: '["[41]", "[42]"]'});
CREATE (:MPKG:HostPopulation {id: 'host_rat', label: 'Rat', organism_class: 'mammal', scientific_name: 'Rattus norvegicus', model_type: 'in_vivo', translational_relevance: 'medium', notes: 'Male rats chronically exposed to 40 nm polystyrene nanoplastics; no behavioral or weight impact reported.'});
CREATE (:MPKG:HostPopulation {id: 'host_european_seabass', label: 'European seabass', organism_class: 'fish', scientific_name: 'Dicentrarchus labrax', model_type: 'in_vivo', translational_relevance: 'low', notes: 'Exposure reduced AChE release, triggered oxidative stress and lipid peroxidation, and altered swimming behavior.', citations_ref: '["[42]"]'});
CREATE (:MPKG:HostPopulation {id: 'host_c_elegans', label: 'C. elegans', organism_class: 'invertebrate', scientific_name: 'Caenorhabditis elegans', model_type: 'in_vivo', translational_relevance: 'low', notes: 'Exposed to spherical polystyrene microplastics (0.1-5 um) at 1 mg/L; excitotoxicity, lowered survival, decreased lifespan.', citations_ref: '["[83]", "[84]"]'});
CREATE (:MPKG:HostPopulation {id: 'host_earthworm', label: 'Earthworm', organism_class: 'invertebrate', scientific_name: 'Eisenia fetida', model_type: 'in_vivo', translational_relevance: 'low', notes: 'Exposed to LDPE particles (100-200 um) in artificial soil; skin damage and oxidative stress markers.', citations_ref: '["[85]"]'});
CREATE (:MPKG:HostPopulation {id: 'host_zebra_mussel', label: 'Zebra mussel', organism_class: 'invertebrate', scientific_name: 'Dreissena polymorpha', model_type: 'in_vivo', translational_relevance: 'low', notes: 'Exposed to polystyrene microbeads (1 and 10 um); particle accumulation, increased dopamine, no genotoxicity.', citations_ref: '["[86]"]'});
CREATE (:MPKG:HostPopulation {id: 'host_scrobicularia', label: 'Peppery furrow shell', organism_class: 'invertebrate', scientific_name: 'Scrobicularia plana', model_type: 'in_vivo', translational_relevance: 'low', notes: 'Exposed to 20 um polystyrene microplastics at 1 mg/L; particles detected in hemolymph, digestive gland, and gills.'});
CREATE (:MPKG:HostPopulation {id: 'host_mediterranean_mussel', label: 'Mediterranean mussel', organism_class: 'invertebrate', scientific_name: 'Mytilus galloprovincialis', model_type: 'in_vivo', translational_relevance: 'low', notes: 'Exposed to polyethylene and polystyrene microplastics (100 um); particles within hemolymph, gills, and intestines.'});
CREATE (:MPKG:HostPopulation {id: 'host_corbicula', label: 'Asian clam', organism_class: 'invertebrate', scientific_name: 'Corbicula fluminea', model_type: 'in_vivo', translational_relevance: 'low', notes: 'Exposed to red fluorescent polymeric microspheres (1-5 um); particles inside digestive tract, gills, and hemolymphatic sinuses.'});
CREATE (:MPKG:HostPopulation {id: 'host_barnacle_brineshrimp_larvae', label: 'Barnacle and brine shrimp larvae', organism_class: 'invertebrate', scientific_name: 'Amphibalanus amphitrite; Artemia franciscana', model_type: 'in_vivo', translational_relevance: 'low', notes: 'Larvae exposed to 0.1 um fluorescent polystyrene microparticles; particles detectable within larvae.'});
CREATE (:MPKG:Evidence {id: 'evidence_mouse_liver_accumulation', text: 'The exposure to polystyrene microplastics led to the absorption and presence of particles in the mice\'s gut, liver, and kidneys, confirmed via fluorescence spectrometer analysis of freeze-dried tissues.', study_ref: 'study_ref_42', section: '8. Neurotoxic Effects in Rodents', quote_verbatim: true, evidence_type: 'in_vivo', confidence: 'high', citations_ref: '["[42]"]'});
CREATE (:MPKG:Evidence {id: 'evidence_mouse_brain_caspase3', text: 'Mouse brain tissues exposed to PS-NH2 showed increased caspase-3 signals, a marker for neuron cell apoptosis.', study_ref: 'study_ref_41', section: '5. Effects on the Nervous System', quote_verbatim: true, evidence_type: 'in_vivo', confidence: 'high', citations_ref: '["[41]"]'});
CREATE (:MPKG:Evidence {id: 'evidence_mouse_brain_cytokines', text: 'Cytokines like TNF-alpha and IL-6 were upregulated in these tissues, hinting at inflammation caused by cytokine presence.', study_ref: 'study_ref_41', section: '5. Effects on the Nervous System', quote_verbatim: true, evidence_type: 'in_vivo', confidence: 'high', citations_ref: '["[41]"]'});
CREATE (:MPKG:Evidence {id: 'evidence_earthworm_uptake', text: 'Upon analyzing and quantifying polyethylene particles, their uptake (after 14-28 days at 1.5 g/kg soil) was confirmed.', study_ref: 'study_ref_85', section: '7. Neurotoxic Effects on Marine Invertebrates', quote_verbatim: true, evidence_type: 'in_vivo', confidence: 'high', citations_ref: '["[85]"]'});
CREATE (:MPKG:Evidence {id: 'evidence_zebra_mussel_accumulation', text: 'This led to the accumulation of particles within the gut lumen and further movement to tissues and hemolymph, as observed with confocal microscopy.', study_ref: 'study_ref_86', section: '7. Neurotoxic Effects on Marine Invertebrates', quote_verbatim: true, evidence_type: 'in_vivo', confidence: 'high', citations_ref: '["[86]"]'});
CREATE (:MPKG:Evidence {id: 'evidence_zebra_mussel_no_genotoxicity', text: 'Importantly, these polystyrene microbeads did not cause genotoxic effects.', study_ref: 'study_ref_86', section: '7. Neurotoxic Effects on Marine Invertebrates', quote_verbatim: true, evidence_type: 'in_vivo', confidence: 'high', citations_ref: '["[86]"]'});

// --- Relationships ---
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'obs_mouse_liver_5um_ps_concentration'}) CREATE (a)-[:REPORTS]->(b);
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'obs_mouse_kidney_5um_ps_concentration'}) CREATE (a)-[:REPORTS]->(b);
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'obs_mouse_gut_5um_ps_concentration'}) CREATE (a)-[:REPORTS]->(b);
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'obs_mouse_20um_ps_concentration_plateau'}) CREATE (a)-[:REPORTS]->(b);
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'obs_earthworm_polyethylene_uptake'}) CREATE (a)-[:REPORTS]->(b);
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'obs_zebra_mussel_polystyrene_microbeads_accumulation'}) CREATE (a)-[:REPORTS]->(b);
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'obs_scrobicularia_polystyrene_particles_detected'}) CREATE (a)-[:REPORTS]->(b);
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'obs_mediterranean_mussel_particles_detected'}) CREATE (a)-[:REPORTS]->(b);
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'obs_corbicula_polymeric_microspheres_detected'}) CREATE (a)-[:REPORTS]->(b);
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'obs_shrimp_polystyrene_particles_detected'}) CREATE (a)-[:REPORTS]->(b);
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'obs_mouse_brain_caspase3_increased'}) CREATE (a)-[:REPORTS]->(b);
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'obs_mouse_brain_tnf_il6_upregulated'}) CREATE (a)-[:REPORTS]->(b);
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'obs_zebra_mussel_no_genotoxic_effects'}) CREATE (a)-[:REPORTS]->(b);
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'assoc_nanoplastics_oxidative_stress'}) CREATE (a)-[:SUPPORTS]->(b);
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'assoc_ache_neurotransmitter_behavioral_changes'}) CREATE (a)-[:SUPPORTS]->(b);
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'assoc_celegans_polystyrene_exposure_effects'}) CREATE (a)-[:SUPPORTS]->(b);
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'assoc_neuronal_gene_decline_disruptions_oxidative_stress'}) CREATE (a)-[:SUPPORTS]->(b);
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'assoc_rat_40nm_ps_null_behavior_weight'}) CREATE (a)-[:SUPPORTS]->(b);
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'assoc_zebra_mussel_genotoxicity_null'}) CREATE (a)-[:SUPPORTS]->(b);
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'mechanism_oxidative_stress'}) CREATE (a)-[:EVALUATES]->(b);
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'mechanism_inflammation'}) CREATE (a)-[:EVALUATES]->(b);
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'mechanism_metabolic_disturbance'}) CREATE (a)-[:EVALUATES]->(b);
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'mechanism_genotoxicity'}) CREATE (a)-[:EVALUATES]->(b);
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'mechanism_apoptosis'}) CREATE (a)-[:EVALUATES]->(b);
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'outcome_behavioral_changes'}) CREATE (a)-[:ASSESSES]->(b);
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'outcome_neurological_disorders'}) CREATE (a)-[:ASSESSES]->(b);
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'outcome_lower_survival_lifespan'}) CREATE (a)-[:ASSESSES]->(b);
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'exposure_oral'}) CREATE (a)-[:INVESTIGATES]->(b);
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'exposure_inhalation'}) CREATE (a)-[:INVESTIGATES]->(b);
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'exposure_nasal_retrograde'}) CREATE (a)-[:INVESTIGATES]->(b);
MATCH (a:MPKG {id: 'obs_mouse_liver_5um_ps_concentration'}), (b:MPKG {id: 'method_fluorescence_spectrometer'}) CREATE (a)-[:IDENTIFIED_BY]->(b);
MATCH (a:MPKG {id: 'obs_mouse_kidney_5um_ps_concentration'}), (b:MPKG {id: 'method_fluorescence_spectrometer'}) CREATE (a)-[:IDENTIFIED_BY]->(b);
MATCH (a:MPKG {id: 'obs_mouse_gut_5um_ps_concentration'}), (b:MPKG {id: 'method_fluorescence_spectrometer'}) CREATE (a)-[:IDENTIFIED_BY]->(b);
MATCH (a:MPKG {id: 'obs_zebra_mussel_polystyrene_microbeads_accumulation'}), (b:MPKG {id: 'method_confocal_microscopy'}) CREATE (a)-[:IDENTIFIED_BY]->(b);
MATCH (a:MPKG {id: 'obs_scrobicularia_polystyrene_particles_detected'}), (b:MPKG {id: 'method_light_microscopy'}) CREATE (a)-[:IDENTIFIED_BY]->(b);
MATCH (a:MPKG {id: 'obs_scrobicularia_polystyrene_particles_detected'}), (b:MPKG {id: 'method_infrared_spectroscopy'}) CREATE (a)-[:IDENTIFIED_BY]->(b);
MATCH (a:MPKG {id: 'obs_mediterranean_mussel_particles_detected'}), (b:MPKG {id: 'method_polarized_light_microscopy'}) CREATE (a)-[:IDENTIFIED_BY]->(b);
MATCH (a:MPKG {id: 'obs_corbicula_polymeric_microspheres_detected'}), (b:MPKG {id: 'method_light_microscopy'}) CREATE (a)-[:IDENTIFIED_BY]->(b);
MATCH (a:MPKG {id: 'obs_corbicula_polymeric_microspheres_detected'}), (b:MPKG {id: 'method_fluorescence_microscopy'}) CREATE (a)-[:IDENTIFIED_BY]->(b);
MATCH (a:MPKG {id: 'obs_shrimp_polystyrene_particles_detected'}), (b:MPKG {id: 'method_fluorescence_microscopy'}) CREATE (a)-[:IDENTIFIED_BY]->(b);
MATCH (a:MPKG {id: 'method_fluorescence_spectrometer'}), (b:MPKG {id: 'obs_mouse_liver_5um_ps_concentration'}) CREATE (a)-[:PRODUCES]->(b);
MATCH (a:MPKG {id: 'method_fluorescence_spectrometer'}), (b:MPKG {id: 'obs_mouse_kidney_5um_ps_concentration'}) CREATE (a)-[:PRODUCES]->(b);
MATCH (a:MPKG {id: 'method_fluorescence_spectrometer'}), (b:MPKG {id: 'obs_mouse_gut_5um_ps_concentration'}) CREATE (a)-[:PRODUCES]->(b);
MATCH (a:MPKG {id: 'method_confocal_microscopy'}), (b:MPKG {id: 'obs_zebra_mussel_polystyrene_microbeads_accumulation'}) CREATE (a)-[:PRODUCES]->(b);
MATCH (a:MPKG {id: 'method_light_microscopy'}), (b:MPKG {id: 'obs_scrobicularia_polystyrene_particles_detected'}) CREATE (a)-[:PRODUCES]->(b);
MATCH (a:MPKG {id: 'method_infrared_spectroscopy'}), (b:MPKG {id: 'obs_scrobicularia_polystyrene_particles_detected'}) CREATE (a)-[:PRODUCES]->(b);
MATCH (a:MPKG {id: 'method_polarized_light_microscopy'}), (b:MPKG {id: 'obs_mediterranean_mussel_particles_detected'}) CREATE (a)-[:PRODUCES]->(b);
MATCH (a:MPKG {id: 'method_light_microscopy'}), (b:MPKG {id: 'obs_corbicula_polymeric_microspheres_detected'}) CREATE (a)-[:PRODUCES]->(b);
MATCH (a:MPKG {id: 'method_fluorescence_microscopy'}), (b:MPKG {id: 'obs_corbicula_polymeric_microspheres_detected'}) CREATE (a)-[:PRODUCES]->(b);
MATCH (a:MPKG {id: 'method_fluorescence_microscopy'}), (b:MPKG {id: 'obs_shrimp_polystyrene_particles_detected'}) CREATE (a)-[:PRODUCES]->(b);
MATCH (a:MPKG {id: 'obs_mouse_liver_5um_ps_concentration'}), (b:MPKG {id: 'polymer_polystyrene'}) CREATE (a)-[:HAS_POLYMER]->(b);
MATCH (a:MPKG {id: 'obs_mouse_kidney_5um_ps_concentration'}), (b:MPKG {id: 'polymer_polystyrene'}) CREATE (a)-[:HAS_POLYMER]->(b);
MATCH (a:MPKG {id: 'obs_mouse_gut_5um_ps_concentration'}), (b:MPKG {id: 'polymer_polystyrene'}) CREATE (a)-[:HAS_POLYMER]->(b);
MATCH (a:MPKG {id: 'obs_mouse_20um_ps_concentration_plateau'}), (b:MPKG {id: 'polymer_polystyrene'}) CREATE (a)-[:HAS_POLYMER]->(b);
MATCH (a:MPKG {id: 'obs_earthworm_polyethylene_uptake'}), (b:MPKG {id: 'polymer_low_density_polyethylene'}) CREATE (a)-[:HAS_POLYMER]->(b);
MATCH (a:MPKG {id: 'obs_zebra_mussel_polystyrene_microbeads_accumulation'}), (b:MPKG {id: 'polymer_polystyrene'}) CREATE (a)-[:HAS_POLYMER]->(b);
MATCH (a:MPKG {id: 'obs_scrobicularia_polystyrene_particles_detected'}), (b:MPKG {id: 'polymer_polystyrene'}) CREATE (a)-[:HAS_POLYMER]->(b);
MATCH (a:MPKG {id: 'obs_mediterranean_mussel_particles_detected'}), (b:MPKG {id: 'polymer_polyethylene'}) CREATE (a)-[:HAS_POLYMER]->(b);
MATCH (a:MPKG {id: 'obs_mediterranean_mussel_particles_detected'}), (b:MPKG {id: 'polymer_polystyrene'}) CREATE (a)-[:HAS_POLYMER]->(b);
MATCH (a:MPKG {id: 'obs_shrimp_polystyrene_particles_detected'}), (b:MPKG {id: 'polymer_polystyrene'}) CREATE (a)-[:HAS_POLYMER]->(b);
MATCH (a:MPKG {id: 'obs_mouse_brain_caspase3_increased'}), (b:MPKG {id: 'polymer_amino_modified_polystyrene'}) CREATE (a)-[:HAS_POLYMER]->(b);
MATCH (a:MPKG {id: 'obs_mouse_brain_tnf_il6_upregulated'}), (b:MPKG {id: 'polymer_amino_modified_polystyrene'}) CREATE (a)-[:HAS_POLYMER]->(b);
MATCH (a:MPKG {id: 'obs_zebra_mussel_no_genotoxic_effects'}), (b:MPKG {id: 'polymer_polystyrene'}) CREATE (a)-[:HAS_POLYMER]->(b);
MATCH (a:MPKG {id: 'obs_mouse_liver_5um_ps_concentration'}), (b:MPKG {id: 'size_5_um'}) CREATE (a)-[:HAS_SIZE_CLASS]->(b);
MATCH (a:MPKG {id: 'obs_mouse_kidney_5um_ps_concentration'}), (b:MPKG {id: 'size_5_um'}) CREATE (a)-[:HAS_SIZE_CLASS]->(b);
MATCH (a:MPKG {id: 'obs_mouse_gut_5um_ps_concentration'}), (b:MPKG {id: 'size_5_um'}) CREATE (a)-[:HAS_SIZE_CLASS]->(b);
MATCH (a:MPKG {id: 'obs_mouse_20um_ps_concentration_plateau'}), (b:MPKG {id: 'size_20_um'}) CREATE (a)-[:HAS_SIZE_CLASS]->(b);
MATCH (a:MPKG {id: 'obs_earthworm_polyethylene_uptake'}), (b:MPKG {id: 'size_100_to_200_um'}) CREATE (a)-[:HAS_SIZE_CLASS]->(b);
MATCH (a:MPKG {id: 'obs_zebra_mussel_polystyrene_microbeads_accumulation'}), (b:MPKG {id: 'size_1_um'}) CREATE (a)-[:HAS_SIZE_CLASS]->(b);
MATCH (a:MPKG {id: 'obs_zebra_mussel_polystyrene_microbeads_accumulation'}), (b:MPKG {id: 'size_10_um'}) CREATE (a)-[:HAS_SIZE_CLASS]->(b);
MATCH (a:MPKG {id: 'obs_scrobicularia_polystyrene_particles_detected'}), (b:MPKG {id: 'size_20_um'}) CREATE (a)-[:HAS_SIZE_CLASS]->(b);
MATCH (a:MPKG {id: 'obs_mediterranean_mussel_particles_detected'}), (b:MPKG {id: 'size_100_um'}) CREATE (a)-[:HAS_SIZE_CLASS]->(b);
MATCH (a:MPKG {id: 'obs_corbicula_polymeric_microspheres_detected'}), (b:MPKG {id: 'size_1_to_5_um'}) CREATE (a)-[:HAS_SIZE_CLASS]->(b);
MATCH (a:MPKG {id: 'obs_shrimp_polystyrene_particles_detected'}), (b:MPKG {id: 'size_0_1_um'}) CREATE (a)-[:HAS_SIZE_CLASS]->(b);
MATCH (a:MPKG {id: 'obs_zebra_mussel_polystyrene_microbeads_accumulation'}), (b:MPKG {id: 'shape_bead'}) CREATE (a)-[:HAS_SHAPE]->(b);
MATCH (a:MPKG {id: 'assoc_nanoplastics_oxidative_stress'}), (b:MPKG {id: 'mechanism_oxidative_stress'}) CREATE (a)-[:LINKS]->(b);
MATCH (a:MPKG {id: 'assoc_nanoplastics_oxidative_stress'}), (b:MPKG {id: 'outcome_neurological_disorders'}) CREATE (a)-[:LINKS]->(b);
MATCH (a:MPKG {id: 'assoc_ache_neurotransmitter_behavioral_changes'}), (b:MPKG {id: 'biomarker_acetylcholinesterase_activity'}) CREATE (a)-[:LINKS]->(b);
MATCH (a:MPKG {id: 'assoc_ache_neurotransmitter_behavioral_changes'}), (b:MPKG {id: 'outcome_behavioral_changes'}) CREATE (a)-[:LINKS]->(b);
MATCH (a:MPKG {id: 'assoc_celegans_polystyrene_exposure_effects'}), (b:MPKG {id: 'outcome_lower_survival_lifespan'}) CREATE (a)-[:LINKS]->(b);
MATCH (a:MPKG {id: 'assoc_neuronal_gene_decline_disruptions_oxidative_stress'}), (b:MPKG {id: 'mechanism_oxidative_stress'}) CREATE (a)-[:LINKS]->(b);
MATCH (a:MPKG {id: 'assoc_rat_40nm_ps_null_behavior_weight'}), (b:MPKG {id: 'outcome_behavioral_changes'}) CREATE (a)-[:LINKS]->(b);
MATCH (a:MPKG {id: 'assoc_zebra_mussel_genotoxicity_null'}), (b:MPKG {id: 'mechanism_genotoxicity'}) CREATE (a)-[:LINKS]->(b);
MATCH (a:MPKG {id: 'assoc_nanoplastics_oxidative_stress'}), (b:MPKG {id: 'study_neurotoxicity_following_exposure_review'}) CREATE (a)-[:SUPPORTED_BY]->(b);
MATCH (a:MPKG {id: 'assoc_ache_neurotransmitter_behavioral_changes'}), (b:MPKG {id: 'study_neurotoxicity_following_exposure_review'}) CREATE (a)-[:SUPPORTED_BY]->(b);
MATCH (a:MPKG {id: 'assoc_celegans_polystyrene_exposure_effects'}), (b:MPKG {id: 'study_neurotoxicity_following_exposure_review'}) CREATE (a)-[:SUPPORTED_BY]->(b);
MATCH (a:MPKG {id: 'assoc_neuronal_gene_decline_disruptions_oxidative_stress'}), (b:MPKG {id: 'study_neurotoxicity_following_exposure_review'}) CREATE (a)-[:SUPPORTED_BY]->(b);
MATCH (a:MPKG {id: 'assoc_rat_40nm_ps_null_behavior_weight'}), (b:MPKG {id: 'study_neurotoxicity_following_exposure_review'}) CREATE (a)-[:SUPPORTED_BY]->(b);
MATCH (a:MPKG {id: 'assoc_zebra_mussel_genotoxicity_null'}), (b:MPKG {id: 'study_neurotoxicity_following_exposure_review'}) CREATE (a)-[:SUPPORTED_BY]->(b);
MATCH (a:MPKG {id: 'mechanism_oxidative_stress'}), (b:MPKG {id: 'biomarker_catalase_activity'}) CREATE (a)-[:EVIDENCED_BY]->(b);
MATCH (a:MPKG {id: 'mechanism_oxidative_stress'}), (b:MPKG {id: 'biomarker_malondialdehyde_levels'}) CREATE (a)-[:EVIDENCED_BY]->(b);
MATCH (a:MPKG {id: 'mechanism_oxidative_stress'}), (b:MPKG {id: 'biomarker_superoxide_dismutase_activity'}) CREATE (a)-[:EVIDENCED_BY]->(b);
MATCH (a:MPKG {id: 'mechanism_oxidative_stress'}), (b:MPKG {id: 'biomarker_lipid_peroxidation'}) CREATE (a)-[:EVIDENCED_BY]->(b);
MATCH (a:MPKG {id: 'mechanism_inflammation'}), (b:MPKG {id: 'biomarker_tnf_alpha'}) CREATE (a)-[:EVIDENCED_BY]->(b);
MATCH (a:MPKG {id: 'mechanism_inflammation'}), (b:MPKG {id: 'biomarker_il_6'}) CREATE (a)-[:EVIDENCED_BY]->(b);
MATCH (a:MPKG {id: 'mechanism_metabolic_disturbance'}), (b:MPKG {id: 'biomarker_atp_levels'}) CREATE (a)-[:EVIDENCED_BY]->(b);
MATCH (a:MPKG {id: 'mechanism_metabolic_disturbance'}), (b:MPKG {id: 'biomarker_ldh_activity'}) CREATE (a)-[:EVIDENCED_BY]->(b);
MATCH (a:MPKG {id: 'mechanism_apoptosis'}), (b:MPKG {id: 'biomarker_caspase_3'}) CREATE (a)-[:EVIDENCED_BY]->(b);
MATCH (a:MPKG {id: 'mechanism_oxidative_stress'}), (b:MPKG {id: 'outcome_neurological_disorders'}) CREATE (a)-[:ASSOCIATED_WITH]->(b);
MATCH (a:MPKG {id: 'mechanism_inflammation'}), (b:MPKG {id: 'tissue_brain'}) CREATE (a)-[:AFFECTS]->(b);
MATCH (a:MPKG {id: 'mechanism_apoptosis'}), (b:MPKG {id: 'tissue_brain'}) CREATE (a)-[:AFFECTS]->(b);
MATCH (a:MPKG {id: 'mechanism_metabolic_disturbance'}), (b:MPKG {id: 'tissue_liver'}) CREATE (a)-[:AFFECTS]->(b);
MATCH (a:MPKG {id: 'biomarker_caspase_3'}), (b:MPKG {id: 'tissue_brain'}) CREATE (a)-[:MEASURED_IN]->(b);
MATCH (a:MPKG {id: 'biomarker_tnf_alpha'}), (b:MPKG {id: 'tissue_brain'}) CREATE (a)-[:MEASURED_IN]->(b);
MATCH (a:MPKG {id: 'biomarker_il_6'}), (b:MPKG {id: 'tissue_brain'}) CREATE (a)-[:MEASURED_IN]->(b);
MATCH (a:MPKG {id: 'biomarker_atp_levels'}), (b:MPKG {id: 'tissue_liver'}) CREATE (a)-[:MEASURED_IN]->(b);
MATCH (a:MPKG {id: 'biomarker_ldh_activity'}), (b:MPKG {id: 'tissue_liver'}) CREATE (a)-[:MEASURED_IN]->(b);
MATCH (a:MPKG {id: 'biomarker_acetylcholinesterase_activity'}), (b:MPKG {id: 'study_neurotoxicity_following_exposure_review'}) CREATE (a)-[:EVALUATED_IN]->(b);
MATCH (a:MPKG {id: 'biomarker_caspase_3'}), (b:MPKG {id: 'study_neurotoxicity_following_exposure_review'}) CREATE (a)-[:EVALUATED_IN]->(b);
MATCH (a:MPKG {id: 'biomarker_tnf_alpha'}), (b:MPKG {id: 'study_neurotoxicity_following_exposure_review'}) CREATE (a)-[:EVALUATED_IN]->(b);
MATCH (a:MPKG {id: 'biomarker_il_6'}), (b:MPKG {id: 'study_neurotoxicity_following_exposure_review'}) CREATE (a)-[:EVALUATED_IN]->(b);
MATCH (a:MPKG {id: 'biomarker_catalase_activity'}), (b:MPKG {id: 'study_neurotoxicity_following_exposure_review'}) CREATE (a)-[:EVALUATED_IN]->(b);
MATCH (a:MPKG {id: 'biomarker_malondialdehyde_levels'}), (b:MPKG {id: 'study_neurotoxicity_following_exposure_review'}) CREATE (a)-[:EVALUATED_IN]->(b);
MATCH (a:MPKG {id: 'biomarker_dopamine_levels'}), (b:MPKG {id: 'study_neurotoxicity_following_exposure_review'}) CREATE (a)-[:EVALUATED_IN]->(b);
MATCH (a:MPKG {id: 'biomarker_superoxide_dismutase_activity'}), (b:MPKG {id: 'study_neurotoxicity_following_exposure_review'}) CREATE (a)-[:EVALUATED_IN]->(b);
MATCH (a:MPKG {id: 'biomarker_glutathione_s_transferase_activity'}), (b:MPKG {id: 'study_neurotoxicity_following_exposure_review'}) CREATE (a)-[:EVALUATED_IN]->(b);
MATCH (a:MPKG {id: 'biomarker_lipid_peroxidation'}), (b:MPKG {id: 'study_neurotoxicity_following_exposure_review'}) CREATE (a)-[:EVALUATED_IN]->(b);
MATCH (a:MPKG {id: 'biomarker_atp_levels'}), (b:MPKG {id: 'study_neurotoxicity_following_exposure_review'}) CREATE (a)-[:EVALUATED_IN]->(b);
MATCH (a:MPKG {id: 'biomarker_ldh_activity'}), (b:MPKG {id: 'study_neurotoxicity_following_exposure_review'}) CREATE (a)-[:EVALUATED_IN]->(b);
MATCH (a:MPKG {id: 'study_ref_41'}), (b:MPKG {id: 'host_mouse'}) CREATE (a)-[:INVESTIGATES]->(b);
MATCH (a:MPKG {id: 'study_ref_42'}), (b:MPKG {id: 'host_mouse'}) CREATE (a)-[:INVESTIGATES]->(b);
MATCH (a:MPKG {id: 'study_ref_85'}), (b:MPKG {id: 'host_earthworm'}) CREATE (a)-[:INVESTIGATES]->(b);
MATCH (a:MPKG {id: 'study_ref_86'}), (b:MPKG {id: 'host_zebra_mussel'}) CREATE (a)-[:INVESTIGATES]->(b);
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'host_human'}) CREATE (a)-[:INVESTIGATES]->(b);
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'host_rat'}) CREATE (a)-[:INVESTIGATES]->(b);
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'host_european_seabass'}) CREATE (a)-[:INVESTIGATES]->(b);
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'host_c_elegans'}) CREATE (a)-[:INVESTIGATES]->(b);
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'host_scrobicularia'}) CREATE (a)-[:INVESTIGATES]->(b);
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'host_mediterranean_mussel'}) CREATE (a)-[:INVESTIGATES]->(b);
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'host_corbicula'}) CREATE (a)-[:INVESTIGATES]->(b);
MATCH (a:MPKG {id: 'study_neurotoxicity_following_exposure_review'}), (b:MPKG {id: 'host_barnacle_brineshrimp_larvae'}) CREATE (a)-[:INVESTIGATES]->(b);
MATCH (a:MPKG {id: 'exposure_oral'}), (b:MPKG {id: 'host_mouse'}) CREATE (a)-[:EXPOSES]->(b);
MATCH (a:MPKG {id: 'exposure_oral'}), (b:MPKG {id: 'host_human'}) CREATE (a)-[:EXPOSES]->(b);
MATCH (a:MPKG {id: 'exposure_inhalation'}), (b:MPKG {id: 'host_human'}) CREATE (a)-[:EXPOSES]->(b);
MATCH (a:MPKG {id: 'exposure_nasal_retrograde'}), (b:MPKG {id: 'host_human'}) CREATE (a)-[:EXPOSES]->(b);
MATCH (a:MPKG {id: 'host_c_elegans'}), (b:MPKG {id: 'outcome_lower_survival_lifespan'}) CREATE (a)-[:EXPERIENCES]->(b);
MATCH (a:MPKG {id: 'host_human'}), (b:MPKG {id: 'outcome_neurological_disorders'}) CREATE (a)-[:EXPERIENCES]->(b);
MATCH (a:MPKG {id: 'host_mouse'}), (b:MPKG {id: 'biomarker_caspase_3'}) CREATE (a)-[:EXHIBITS]->(b);
MATCH (a:MPKG {id: 'host_mouse'}), (b:MPKG {id: 'biomarker_tnf_alpha'}) CREATE (a)-[:EXHIBITS]->(b);
MATCH (a:MPKG {id: 'host_mouse'}), (b:MPKG {id: 'biomarker_il_6'}) CREATE (a)-[:EXHIBITS]->(b);
MATCH (a:MPKG {id: 'host_mouse'}), (b:MPKG {id: 'biomarker_atp_levels'}) CREATE (a)-[:EXHIBITS]->(b);
MATCH (a:MPKG {id: 'host_mouse'}), (b:MPKG {id: 'biomarker_ldh_activity'}) CREATE (a)-[:EXHIBITS]->(b);
MATCH (a:MPKG {id: 'host_earthworm'}), (b:MPKG {id: 'biomarker_catalase_activity'}) CREATE (a)-[:EXHIBITS]->(b);
MATCH (a:MPKG {id: 'host_earthworm'}), (b:MPKG {id: 'biomarker_malondialdehyde_levels'}) CREATE (a)-[:EXHIBITS]->(b);
MATCH (a:MPKG {id: 'host_earthworm'}), (b:MPKG {id: 'biomarker_acetylcholinesterase_activity'}) CREATE (a)-[:EXHIBITS]->(b);
MATCH (a:MPKG {id: 'host_zebra_mussel'}), (b:MPKG {id: 'biomarker_dopamine_levels'}) CREATE (a)-[:EXHIBITS]->(b);
MATCH (a:MPKG {id: 'study_ref_42'}), (b:MPKG {id: 'evidence_mouse_liver_accumulation'}) CREATE (a)-[:PROVIDES]->(b);
MATCH (a:MPKG {id: 'study_ref_41'}), (b:MPKG {id: 'evidence_mouse_brain_caspase3'}) CREATE (a)-[:PROVIDES]->(b);
MATCH (a:MPKG {id: 'study_ref_41'}), (b:MPKG {id: 'evidence_mouse_brain_cytokines'}) CREATE (a)-[:PROVIDES]->(b);
MATCH (a:MPKG {id: 'study_ref_85'}), (b:MPKG {id: 'evidence_earthworm_uptake'}) CREATE (a)-[:PROVIDES]->(b);
MATCH (a:MPKG {id: 'study_ref_86'}), (b:MPKG {id: 'evidence_zebra_mussel_accumulation'}) CREATE (a)-[:PROVIDES]->(b);
MATCH (a:MPKG {id: 'study_ref_86'}), (b:MPKG {id: 'evidence_zebra_mussel_no_genotoxicity'}) CREATE (a)-[:PROVIDES]->(b);
MATCH (a:MPKG {id: 'evidence_mouse_liver_accumulation'}), (b:MPKG {id: 'obs_mouse_liver_5um_ps_concentration'}) CREATE (a)-[:SUPPORTS]->(b);
MATCH (a:MPKG {id: 'evidence_mouse_brain_caspase3'}), (b:MPKG {id: 'obs_mouse_brain_caspase3_increased'}) CREATE (a)-[:SUPPORTS]->(b);
MATCH (a:MPKG {id: 'evidence_mouse_brain_cytokines'}), (b:MPKG {id: 'obs_mouse_brain_tnf_il6_upregulated'}) CREATE (a)-[:SUPPORTS]->(b);
MATCH (a:MPKG {id: 'evidence_earthworm_uptake'}), (b:MPKG {id: 'obs_earthworm_polyethylene_uptake'}) CREATE (a)-[:SUPPORTS]->(b);
MATCH (a:MPKG {id: 'evidence_zebra_mussel_accumulation'}), (b:MPKG {id: 'obs_zebra_mussel_polystyrene_microbeads_accumulation'}) CREATE (a)-[:SUPPORTS]->(b);
MATCH (a:MPKG {id: 'evidence_zebra_mussel_no_genotoxicity'}), (b:MPKG {id: 'obs_zebra_mussel_no_genotoxic_effects'}) CREATE (a)-[:SUPPORTS]->(b);
